
# 📘 Arrays in Programming

An **Array** is a **collection of elements** (values or variables), each identified by an **index**.  
Arrays are one of the most fundamental data structures in programming, used to store multiple items of the same type in a single variable.

---

## ✨ Key Points:
- Arrays are **contiguous memory locations**.
- They allow **random access** using indexes.
- Array index starts from **0** in most programming languages (like C, C++, Java, Python).
- Fixed size: Once declared, the size of an array usually cannot be changed.

---

## 🔑 Definition:
An array is a data structure consisting of a collection of elements, each identified by at least one array index or key.

---

## 📊 Example Diagram:

### Array of Size 5:
```
Index:   0    1    2    3    4
Value:  10   20   30   40   50
```

This means:
- `arr[0] = 10`
- `arr[1] = 20`
- `arr[2] = 30`
- `arr[3] = 40`
- `arr[4] = 50`

---

## ✅ Operations on Arrays:
1. **Traversal** – Accessing each element one by one.
2. **Insertion** – Adding a new element (at the beginning, middle, or end).
3. **Deletion** – Removing an element from a specific position.
4. **Searching** – Finding the position of an element (Linear Search, Binary Search).
5. **Updation** – Modifying an existing element.

---


**A NumPy array (also called ndarray) is a special type of array provided by the NumPy library.**

Stores elements of the same data type (all integers, all floats, etc.).

Supports fast mathematical operations (addition, multiplication, etc.) directly on the whole array.

In [2]:
import numpy as np

**1.Basic Array creation**

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

*Lists can store different datatypes*


In [4]:
my_list=[1,2,3,"hello"]
my_list

[1, 2, 3, 'hello']

*But array can only store same datatype(e.g it will convert all integers to string-Typecasting)*


In [5]:
arr1=np.array(my_list)
arr1

array(['1', '2', '3', 'hello'], dtype='<U21')

2-Dimensional Array(Matrix)

In [6]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**2.Array generation function**

In [7]:
np.arange(1,11)   #Here 11 is exclusive

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)  #prints numbers from 1 to 10 but with a gap of 2 each

array([1, 3, 5, 7, 9])

Generate array of zeros

In [9]:
np.zeros(6)    #1-Dimensional

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,8))    #1-Dimensional

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Generate array of ones

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((7,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

linspace()-->returns evenly spaced numbers over a specified interval

In [13]:
arr=np.linspace(1,5,4)    # prints 4 evenly spaced numbers between 1 and 5 (inclusive)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

**3.Random generation function**

In [14]:
arr=np.random.rand(5)     # normalization(prints values between 0 and 1)
arr

array([0.45815362, 0.01867407, 0.72365846, 0.80950581, 0.96529127])

In [15]:
arr=np.random.randn(6)    # standarization(prints values between -3 and 3)
arr

array([-0.26555895,  0.24521443,  1.082294  , -0.82582657,  0.15521409,
       -1.04919925])

In [16]:
arr=np.random.randint(6,12,10)   # prints 10 random numbers between 6 and 12 (exclusive) 
arr

array([ 8, 10, 11, 10, 10,  6,  7,  8,  9, 11], dtype=int32)

**4.Array Attributes**

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

**5.Array Methods**

In [24]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.min()   # prints minimum element in whole array-->1

np.int64(1)

In [30]:
arr.max()    # prints maximun element in whole array-->9

np.int64(9)

In [37]:
arr.sum()    # prints the sum of whole array

np.int64(45)

In [38]:
np.sum(arr,axis=0)   # prints sum of each column

array([12, 15, 18])

In [39]:
np.sum(arr,axis=1)   # prints sum of each row

array([ 6, 15, 24])

In [40]:
arr.mean()     # prints the mean of array

np.float64(5.0)

In [41]:
arr.std()      # prints the standard deviation

np.float64(2.581988897471611)

In [43]:
arr.argmax()    # prints the maximum or last index number

np.int64(8)

In [44]:
arr.argmin()    # prints the minimum or first index number

np.int64(0)

**5. Reshaping and Resizing**

In [46]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
arr.reshape(6,5)   # number of rows x columns must be compatible with total number of elements-->2D array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
arr.reshape(2,3,5)   # 3D array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

Resizing

In [51]:
a=arr.reshape(6,5)   # just store it in a variable
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])


## 📌 Array Traversal Example (Visualization)

Suppose we have an array:  
`arr = [5, 10, 15, 20]`

Traversal means visiting each element one by one:

```
for i in range(0, 4):
    print(arr[i])
```

### Diagram:
```
Index →   0     1     2     3
Value →   5    10    15    20
```



# 📝 Summary of Arrays

- Arrays store **multiple values of the same type**.  
- They use **indexes for direct access**.  
- Common operations: **Traversal, Insertion, Deletion, Searching, Updation**.  
- Arrays are the **foundation** for advanced data structures like **Matrices, Strings, Linked Lists, Stacks, and Queues**.  

---

✅ Mastering arrays is essential before moving to more advanced data structures!
