In [1]:
import numpy as np

**Numpy indexing and slicing of vectors**

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[5]   #indexing starting from 0

np.int64(16)

Slicing

In [7]:
arr[1:5]   # prints values from index 1 to 4 (5 is exclusive)

array([12, 13, 14, 15])

In [9]:
arr[:6]    # prints from start till given index

array([11, 12, 13, 14, 15, 16])

In [10]:
arr[2:]   # prints from given index till end

array([13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[:]    # prints from start to end

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
arr[1:9:2]   # prints elements from index 1 to 8 with 2 steps each

array([12, 14, 16, 18])

**Numpy indexing and slicing of Matrix**

In [23]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
arr[4]   # prints a specific row based on its index in case of a matrix

array([21, 22, 23, 24, 25])

In [25]:
arr[2,3]  # prints the element on second row and third column of matrix

np.int64(14)

In [29]:
slice=arr[0:2,1:3]   # slice elememts on specific row and column
slice

array([[2, 3],
       [7, 8]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [33]:
arr[:,3]   # prints a specific column based on its index in case of a matrix

array([ 4,  9, 14, 19, 24, 29])

**Boolean indexing**

In [47]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [49]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

## 🔹 What is NumPy?
NumPy is a powerful Python library for numerical computing.
- Provides arrays that are **faster and more memory-efficient** than Python lists.
- Supports **vectorized operations** (apply operations on entire arrays without loops).
- Useful in data science, ML, image processing, etc.

## 🔹 Indexing
- NumPy uses **0-based indexing** (first element at index 0).
- Supports **positive and negative indexing**.

In [ ]:
arr = np.arange(11,21)
print('Array:', arr)
print('arr[0] →', arr[0])
print('arr[-1] →', arr[-1])  # last element
print('arr[-2] →', arr[-2])  # second last

## 🔹 Slicing
General form: `arr[start:stop:step]`
- `arr[2:6]` → elements from index 2 to 5
- `arr[:5]` → first 5 elements
- `arr[::2]` → every second element
- `arr[::-1]` → reversed array

In [ ]:
print('arr[2:6] →', arr[2:6])
print('arr[:5] →', arr[:5])
print('arr[::2] →', arr[::2])
print('arr[::-1] →', arr[::-1])

## 🔹 Copy vs View (Shallow vs Deep Copy)
- **Slicing** creates a **view** (changes affect the original array).
- Use `.copy()` to make a deep copy.

In [ ]:
arr = np.arange(10)
slice_view = arr[:5]   # view (shallow copy)
slice_view[0] = 99
print('Modified slice:', slice_view)
print('Original array also changed:', arr)

arr_copy = arr[:5].copy()   # deep copy
arr_copy[0] = -1
print('Deep copy modified:', arr_copy)
print('Original array unaffected:', arr)

## 🔹 2D Array Indexing
- Access rows and columns with `[row, col]`
- Use `:` for slicing rows/columns.

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('2D Array:\n', arr2d)
print('arr2d[1,2] →', arr2d[1,2])   # row 1, col 2
print('arr2d[:,1] →', arr2d[:,1])   # all rows, 2nd column

## 🔹 Fancy Indexing
- Select elements using a list/array of indices.

In [ ]:
arr = np.arange(10,20)
print('Array:', arr)
print('arr[[0,2,4]] →', arr[[0,2,4]])

## 🔹 Boolean Indexing
- Select elements based on conditions.

In [ ]:
arr = np.arange(10,20)
print('Array:', arr)
print('arr[arr > 15] →', arr[arr > 15])